### ISSUE TITLE
Add a .clang-format file as Code Style Specification (IDFGH-15214)

### ISSUE THREAD

**Issue by shishirong** [espressif/esp-idf#15884]
### Is your feature request related to a problem?

I dont know how to set clang-format file for keep unified code style specification with esp-idf.

### Describe the solution you'd like.

add a .clang-format file that esp-idf currently in use.

### Describe alternatives you've considered.

keep unified code style specification with esp-idf

**Comment by igrr** [comment]
@shishirong It is not very clear just from the title, what feature you are requesting. Could you please expand your request, answering the first three questions from the issue template? Thank you.

**Comment by dobairoland** [comment]
@shishirong We currently don't use clang-format. If you want to produce the same style as ESP-IDF then you can use https://github.com/espressif/astyle_py. You can either run it locally or setup pre-commit hooks for your project. This is our formatting check:

```yaml
  - repo: https://github.com/espressif/astyle_py.git
    rev: v1.0.5
    hooks:
      - id: astyle_py
        # If you are modifying astyle version, update tools/format.sh as well
        args: ['--astyle-version=3.4.7', '--rules=tools/ci/astyle-rules.yml']
```

and you can find it in https://github.com/espressif/esp-idf/blob/master/.pre-commit-config.yaml.
