### ISSUE TITLE
libsodium component fails with new idf-component-manager on esp-idf v4.4 (IDFGH-7773)

### ISSUE THREAD

**Issue by dot4qu** [espressif/esp-idf#9309]
## Environment

- Development Kit:      none
- Module or chip used: N/A
- IDF version (run ``git describe --tags`` to find it):
  v4.4
- Build System: idf.py
- Compiler version (run ``xtensa-esp32-elf-gcc --version`` to find it):
    8.4.0
- Operating System:    macOS
- Using an IDE?: No
- Power Supply: N/A

## Problem Description

idf-component-manager has an issue with libsodium component on esp-idf v4.4 but not v5.0. No board/chip necessary, error happens in build/compilation.

### Expected Behavior

Component downloaded and compiled in both.

### Actual Behavior

Compiles fine when using latest master branch of esp-idf, but `idf build` fails on v4.4.

The libsodium dependency was added with the command specified in the component manager registry (https://components.espressif.com/component/espressif/libsodium): 
`idf.py add-dependency espressif/libsodium==1.0.20`

This is the v4.4 error output:
```
CMake Error at /Users/user/Developer/esp/esp-idf/tools/cmake/component.cmake:238 (message):
  ERROR: Cannot process component requirements.  Multiple candidates to
  satisfy project requirements:

    requirement: "libsodium" candidates: "libsodium, espressif__libsodium"

Call Stack (most recent call first):
  /Users/user/Developer/esp/esp-idf/tools/cmake/build.cmake:491 (__component_get_requirements)
  /Users/user/Developer/esp/esp-idf/tools/cmake/project.cmake:378 (idf_build_process)
  CMakeLists.txt:14 (project)
```

Here is the idf_component.yml file located in the main/ directory:

```
## IDF Component Manager Manifest File
# This file is only required since ESP-IDF v5.
dependencies:
  espressif/libsodium: "==1.0.20"
  ## Required IDF version
  idf:
    version: ">=4.1"
  # # Put list of dependencies here
  # # For components maintained by Espressif:
  # component: "~1.0.0"
  # # For 3rd party components:
  # username/component: ">=1.0.0,<2.0.0"
  # username2/component2:
  #   version: "~1.0.0"
  #   # For transient dependencies `public` flag can be set.
  #   # `public` flag doesn't have an effect dependencies of the `main` component.
  #   # All dependencies of `main` are public by default.
  #   public: true
```

Here is the generated depencies.lock file:
```
dependencies:
  espressif/libsodium:
    component_hash: 36e9832f40c909c0a9135a3e775fcbdd7a2a13d47a1c052ee5b21499eb3eddb5
    source:
      service_url: https://api.components.espressif.com/
      type: service
    version: 1.0.20
  idf:
    component_hash: null
    source:
      type: idf
    version: 5.0.0
manifest_hash: 733ca58a2c360c30a6a892a31857491a3db091336ff54fabba4a5fc066b6af06
target: esp32
version: 1.0.0
```

**Comment by kumekay** [comment]
@dot4qu Could you please try manifest like this:

```
dependencies:
  espressif/libsodium:
    version: "==1.0.20"
    rules:
      - if: "idf_version >=5.0"
  idf:
    version: ">=4.1"
```

`libsodium` was a part of ESP-IDF till 4.4 and was removed in 5.0. To avoid solver confusion, you can add it conditionally.
