### ISSUE TITLE
esp_event.h: No such file or directory (IDFGH-8032)

### ISSUE THREAD

**Issue by thxmxx** [espressif/esp-idf#9539]
I'm trying to link my project (idf 5) with `esp_modem` but I'm getting the following error:

`... managed_components/espressif__esp_modem/include/cxx_include/esp_modem_primitives.hpp:17:10: fatal error: esp_event.h: No such file or directory`

### idf_component.yml:
```
## IDF Component Manager Manifest File
dependencies:
  espressif/esp_modem: "==0.1.18"
  espressif/coap: "==4.3.1-rc.1"
  ## Required IDF version
  idf:
    version: ">=4.4.0"
  # # Put list of dependencies here
  # # For components maintained by Espressif:
  # component: "~1.0.0"
  # # For 3rd party components:
  # username/component: ">=1.0.0,<2.0.0"
  # username2/component2:
  #   version: "~1.0.0"
  #   # For transient dependencies `public` flag can be set.
  #   # `public` flag doesn't have an effect dependencies of the `main` component.
  #   # All dependencies of `main` are public by default.
  #   public: true
```

### Main CMakeLists.txt

```
idf_component_register(SRCS "bt.c" "main.c"
                    INCLUDE_DIRS "." REQUIRES esp_event driver nvs_flash bt esp_timer GSM)

target_compile_options(${COMPONENT_LIB} PRIVATE "-Wno-format" "-Wno-implicit-function-declaration" "-Wno-cpp" "-Wno-unused-variable")
```

Can someone help me?
